from rest_framework import serializers

class ArticleListSerializer(serializers.Serializer):
    id = serializers.CharField(read_only=True)
    title = serializers.CharField()
    slug = serializers.CharField()
    excerpt = serializers.CharField()
    featuredImage = serializers.CharField()
    thumbnail = serializers.CharField()
    category = serializers.DictField()
    author = serializers.DictField()
    tags = serializers.ListField()
    readTime = serializers.IntegerField()
    isFeatured = serializers.BooleanField()
    viewsCount = serializers.IntegerField()
    likesCount = serializers.IntegerField()
    publishedAt = serializers.CharField()


class ArticleDetailSerializer(serializers.Serializer):
    id = serializers.CharField(read_only=True)
    title = serializers.CharField()
    slug = serializers.CharField()
    content = serializers.CharField()
    excerpt = serializers.CharField()
    featuredImage = serializers.CharField()
    thumbnail = serializers.CharField()
    category = serializers.DictField()
    author = serializers.DictField()
    tags = serializers.ListField()
    readTime = serializers.IntegerField()
    isPublished = serializers.BooleanField()
    isFeatured = serializers.BooleanField()
    viewsCount = serializers.IntegerField()
    likesCount = serializers.IntegerField()
    metaTitle = serializers.CharField(allow_null=True, required=False)
    metaDescription = serializers.CharField(allow_null=True, required=False)
    createdAt = serializers.CharField()
    updatedAt = serializers.CharField()
    publishedAt = serializers.CharField()
