import type { ScientistListItem, ScientistProfile } from './types';
import { SCIENTIST_BIOGRAPHIES } from './scientist-biographies';

const BASE_SCIENTISTS: ScientistProfile[] = [
  {
    id: '1',
    name: 'Albert Einstein',
    slug: 'albert-einstein',
    portraitImage: '/images/scientists/einstein.jpg',
    birthDate: '1879-03-14',
    deathDate: '1955-04-18',
    nationality: 'German-American',
    era: '20th Century',
    field: 'Theoretical Physics',
    group: 'Physical Sciences',
    breakthrough: 'Reframed space, time, gravity, and energy through relativity.',
    biography: 'Albert Einstein transformed modern physics by showing that space and time form a single dynamic fabric. His work connected mass and energy, explained the photoelectric effect, and replaced Newtonian gravity with the geometric theory of general relativity.',
    keyContributions: [
      'Developed special relativity and the mass-energy relation E = mc².',
      'Created general relativity, describing gravity as curved spacetime.',
      'Explained the photoelectric effect using light quanta, helping launch quantum physics.',
    ],
    famousQuotes: [],
    awards: ['Nobel Prize in Physics (1921)', 'Copley Medal (1925)'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Albert_Einstein',
    isFeatured: true,
  },
  {
    id: '2',
    name: 'Marie Curie',
    slug: 'marie-curie',
    portraitImage: '/images/scientists/curie.jpg',
    birthDate: '1867-11-07',
    deathDate: '1934-07-04',
    nationality: 'Polish-French',
    era: '19th-20th Century',
    field: 'Physics & Chemistry',
    group: 'Physical Sciences',
    breakthrough: 'Pioneered radioactivity and opened a new era in atomic science and medicine.',
    biography: 'Marie Curie established the science of radioactivity and developed methods for isolating radioactive isotopes. Her discoveries reshaped physics and chemistry and helped bring mobile X-ray services to wounded soldiers during the First World War.',
    keyContributions: [
      'Discovered the elements polonium and radium with Pierre Curie.',
      'Developed techniques for isolating radioactive isotopes.',
      'Led wartime mobile radiography units that expanded medical X-ray use.',
    ],
    famousQuotes: [],
    awards: ['Nobel Prize in Physics (1903)', 'Nobel Prize in Chemistry (1911)'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Marie_Curie',
    isFeatured: true,
  },
  {
    id: '3',
    name: 'Nikola Tesla',
    slug: 'nikola-tesla',
    portraitImage: '/images/scientists/tesla.jpg',
    birthDate: '1856-07-10',
    deathDate: '1943-01-07',
    nationality: 'Serbian-American',
    era: '19th-20th Century',
    field: 'Electrical Engineering',
    group: 'Physical Sciences',
    breakthrough: 'Made alternating-current power practical on a global scale.',
    biography: 'Nikola Tesla was an inventor and electrical engineer whose polyphase alternating-current system enabled efficient power generation and long-distance transmission. His motors, transformers, and high-frequency experiments helped define the electrical age.',
    keyContributions: [
      'Developed the polyphase AC induction motor and power system.',
      'Invented the Tesla coil for high-voltage, high-frequency experiments.',
      'Advanced radio control, wireless transmission, and rotating magnetic fields.',
    ],
    famousQuotes: [],
    awards: ['Edison Medal (1917)', 'The SI unit tesla is named in his honor'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Nikola_Tesla',
    isFeatured: false,
  },
  {
    id: '4',
    name: 'Stephen Hawking',
    slug: 'stephen-hawking',
    portraitImage: '/images/scientists/hawking.jpg',
    birthDate: '1942-01-08',
    deathDate: '2018-03-14',
    nationality: 'British',
    era: '20th-21st Century',
    field: 'Cosmology & Theoretical Physics',
    group: 'Physical Sciences',
    breakthrough: 'Connected black holes, thermodynamics, and quantum theory.',
    biography: 'Stephen Hawking investigated the origin and structure of the universe. His demonstration that black holes can emit thermal radiation connected quantum mechanics, gravity, and thermodynamics in a way that continues to shape fundamental physics.',
    keyContributions: [
      'Predicted Hawking radiation from black holes.',
      'Proved major singularity theorems with Roger Penrose.',
      'Brought modern cosmology to a worldwide public audience.',
    ],
    famousQuotes: [],
    awards: ['Copley Medal (2006)', 'Presidential Medal of Freedom (2009)'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Stephen_Hawking',
    isFeatured: false,
  },
  {
    id: '5',
    name: 'Isaac Newton',
    slug: 'isaac-newton',
    portraitImage: '/images/scientists/newton.jpg',
    birthDate: '1643-01-04',
    deathDate: '1727-03-31',
    nationality: 'English',
    era: '17th-18th Century',
    field: 'Physics & Mathematics',
    group: 'Physical Sciences',
    breakthrough: 'Unified motion on Earth and in the heavens with mathematical laws.',
    biography: 'Isaac Newton built a mathematical framework for classical mechanics and universal gravitation. His work on calculus, optics, and motion became the foundation of physical science and engineering for centuries.',
    keyContributions: [
      'Formulated the three laws of motion and universal gravitation.',
      'Developed foundational methods of calculus.',
      'Showed that white light is composed of a spectrum of colors.',
    ],
    famousQuotes: [],
    awards: ['Knighted in 1705', 'President of the Royal Society (1703-1727)'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Isaac_Newton',
    isFeatured: false,
  },
  {
    id: '6',
    name: 'Ada Lovelace',
    slug: 'ada-lovelace',
    portraitImage: '/images/scientists/lovelace.jpg',
    birthDate: '1815-12-10',
    deathDate: '1852-11-27',
    nationality: 'British',
    era: '19th Century',
    field: 'Mathematics & Computing',
    group: 'Computing & Algorithms',
    breakthrough: 'Published the first algorithm designed for a general-purpose machine.',
    biography: 'Ada Lovelace recognized that Charles Babbage\'s Analytical Engine could manipulate symbols as well as numbers. Her notes contained a detailed procedure for calculating Bernoulli numbers and anticipated the broader possibilities of programmable computers.',
    keyContributions: [
      'Published an algorithm for the Analytical Engine to compute Bernoulli numbers.',
      'Envisioned computers working with music, text, and symbols—not only arithmetic.',
      'Explained concepts resembling loops and reusable operations in machine computation.',
    ],
    famousQuotes: [],
    awards: ['The Ada programming language was named in her honor'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Ada_Lovelace',
    isFeatured: true,
  },
  {
    id: '7',
    name: 'Al-Khwarizmi',
    slug: 'al-khwarizmi',
    portraitImage: '/images/scientists/al-khwarizmi.jpg',
    birthDate: 'c. 780',
    deathDate: 'c. 850',
    nationality: 'Khwarazmian-Persian',
    era: 'Islamic Golden Age',
    field: 'Mathematics & Algorithms',
    group: 'Arab & Muslim Pioneers',
    breakthrough: 'Founded algebra as a systematic discipline; “algorithm” derives from his name.',
    biography: 'Muhammad ibn Musa al-Khwarizmi worked at Baghdad\'s House of Wisdom. His Arabic works organized algebraic problem-solving into clear procedures and helped transmit Hindu-Arabic numerals and decimal calculation across the medieval world.',
    keyContributions: [
      'Wrote a foundational treatise that gave algebra its name.',
      'Systematized step-by-step calculation methods that shaped the concept of algorithms.',
      'Produced influential works in astronomy, geography, and mathematical tables.',
    ],
    famousQuotes: [],
    awards: ['A lunar crater and asteroid 13498 Al Chwarizmi bear his name'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Al-Khwarizmi',
    isFeatured: true,
  },
  {
    id: '8',
    name: 'Ibn al-Haytham',
    slug: 'ibn-al-haytham',
    portraitImage: '/images/scientists/ibn-al-haytham.jpg',
    birthDate: 'c. 965',
    deathDate: 'c. 1040',
    nationality: 'Arab-Iraqi',
    era: 'Islamic Golden Age',
    field: 'Optics, Physics & Mathematics',
    group: 'Arab & Muslim Pioneers',
    breakthrough: 'Rebuilt optics around experiment, mathematics, and the way light enters the eye.',
    biography: 'Ibn al-Haytham, known in Latin as Alhazen, was an Arab physicist and mathematician whose Book of Optics replaced older emission theories of vision with a testable account based on light entering the eye. His experimental approach strongly influenced later science.',
    keyContributions: [
      'Explained vision through light reflected from objects into the eye.',
      'Used controlled experiments and mathematical reasoning to study optics.',
      'Investigated reflection, refraction, camera obscura, and visual perception.',
    ],
    famousQuotes: [],
    awards: ['UNESCO celebrated the International Year of Light around his optical legacy'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Ibn_al-Haytham',
    isFeatured: true,
  },
  {
    id: '9',
    name: 'Ibn Sina (Avicenna)',
    slug: 'ibn-sina',
    portraitImage: '/images/scientists/ibn-sina.jpg',
    birthDate: 'c. 980',
    deathDate: '1037',
    nationality: 'Persian',
    era: 'Islamic Golden Age',
    field: 'Medicine & Philosophy',
    group: 'Arab & Muslim Pioneers',
    breakthrough: 'Created a systematic medical encyclopedia used across continents for centuries.',
    biography: 'Ibn Sina was a Persian physician and philosopher whose Canon of Medicine synthesized clinical knowledge into an organized reference. Translated into Latin, it became one of the most influential medical texts in both the Islamic world and Europe.',
    keyContributions: [
      'Authored The Canon of Medicine, a landmark medical encyclopedia.',
      'Systematized diagnosis, pharmacology, clinical observation, and treatment.',
      'Made enduring contributions to logic, philosophy, and theories of knowledge.',
    ],
    famousQuotes: [],
    awards: ['A lunar crater and asteroid 2755 Avicenna bear his name'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Avicenna',
    isFeatured: false,
  },
  {
    id: '10',
    name: 'Al-Zahrawi',
    slug: 'al-zahrawi',
    portraitImage: '/images/scientists/al-zahrawi.png',
    birthDate: 'c. 936',
    deathDate: '1013',
    nationality: 'Arab-Andalusian',
    era: 'Islamic Golden Age',
    field: 'Surgery & Medicine',
    group: 'Arab & Muslim Pioneers',
    breakthrough: 'Turned surgery into a documented discipline with specialized instruments and procedures.',
    biography: 'Al-Zahrawi was an Arab physician and surgeon from al-Andalus. The surgical volume of his medical encyclopedia Al-Tasrif illustrated instruments and described practical procedures that remained influential in Europe for centuries.',
    keyContributions: [
      'Documented numerous surgical tools and procedures in Al-Tasrif.',
      'Advanced cauterization, obstetrics, dentistry, and wound treatment.',
      'Helped establish surgery as a respected branch of medicine.',
    ],
    famousQuotes: [],
    awards: ['Remembered as one of the great surgeons of the Middle Ages'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Al-Zahrawi',
    isFeatured: false,
  },
  {
    id: '11',
    name: 'Al-Biruni',
    slug: 'al-biruni',
    portraitImage: '/images/scientists/al-biruni.jpg',
    birthDate: '973-09-04',
    deathDate: 'c. 1050',
    nationality: 'Khwarazmian-Persian',
    era: 'Islamic Golden Age',
    field: 'Astronomy & Geodesy',
    group: 'Arab & Muslim Pioneers',
    breakthrough: 'Measured Earth with remarkable precision and pioneered comparative scientific study.',
    biography: 'Al-Biruni was a polymath who combined astronomy, mathematics, geography, and careful observation. He devised geometric methods for estimating Earth\'s radius and wrote a detailed comparative study of Indian culture and science.',
    keyContributions: [
      'Developed a trigonometric method for estimating Earth\'s radius.',
      'Advanced geodesy, astronomy, cartography, and the study of specific gravity.',
      'Produced an unusually rigorous comparative study of India and its sciences.',
    ],
    famousQuotes: [],
    awards: ['A lunar crater and asteroid 9936 Al-Biruni bear his name'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Al-Biruni',
    isFeatured: false,
  },
  {
    id: '12',
    name: 'Jabir ibn Hayyan',
    slug: 'jabir-ibn-hayyan',
    portraitImage: '/images/scientists/jabir-ibn-hayyan.jpg',
    birthDate: 'c. 721',
    deathDate: 'c. 815',
    nationality: 'Arab-Persian',
    era: 'Islamic Golden Age',
    field: 'Alchemy & Early Chemistry',
    group: 'Arab & Muslim Pioneers',
    breakthrough: 'The Jabirian tradition made laboratory operations central to the study of substances.',
    biography: 'Jabir ibn Hayyan is the figure associated with a large and historically complex corpus of Arabic works on alchemy, chemistry, medicine, and philosophy. The texts attributed to him emphasized materials, apparatus, and repeatable laboratory operations.',
    keyContributions: [
      'Expanded practical methods such as distillation, crystallization, and calcination.',
      'Described laboratory apparatus and systematic manipulation of substances.',
      'Influenced Arabic and later Latin traditions of alchemy and early chemistry.',
    ],
    famousQuotes: [],
    awards: ['The authorship of the wider Jabirian corpus remains an active historical question'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Jabir_ibn_Hayyan',
    isFeatured: false,
  },
  {
    id: '13',
    name: 'Al-Jazari',
    slug: 'al-jazari',
    portraitImage: '/images/scientists/al-jazari.png',
    birthDate: '1136',
    deathDate: '1206',
    nationality: 'Mesopotamian',
    era: 'Islamic Golden Age',
    field: 'Mechanical Engineering & Robotics',
    group: 'Arab & Muslim Pioneers',
    breakthrough: 'Designed programmable automata, pumps, and mechanisms centuries before modern robotics.',
    biography: 'Al-Jazari was an engineer and inventor from Upper Mesopotamia. His illustrated Book of Knowledge of Ingenious Mechanical Devices documented fifty machines with construction instructions, combining hydraulics, gears, automata, and practical design.',
    keyContributions: [
      'Designed water-raising machines, pumps, clocks, and mechanical automata.',
      'Documented a crank-and-connecting-rod mechanism for rotary motion.',
      'Created celebrated programmable musical automata and the elephant clock.',
    ],
    famousQuotes: [],
    awards: ['Often described as a foundational figure in robotics and mechanical engineering'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Ismail_al-Jazari',
    isFeatured: false,
  },
  {
    id: '14',
    name: 'Ibn al-Nafis',
    slug: 'ibn-al-nafis',
    portraitImage: '/images/scientists/ibn-al-nafis.jpg',
    birthDate: '1213',
    deathDate: '1288',
    nationality: 'Arab-Syrian',
    era: 'Islamic Golden Age',
    field: 'Medicine & Physiology',
    group: 'Arab & Muslim Pioneers',
    breakthrough: 'Correctly described pulmonary circulation centuries before it was recognized in Europe.',
    biography: 'Ibn al-Nafis was an Arab physician who rejected important parts of Galen\'s account of the heart. He explained that blood travels from the right side of the heart to the lungs and returns to the left side, establishing the pulmonary circuit.',
    keyContributions: [
      'Gave the earliest known accurate description of pulmonary circulation.',
      'Challenged Galenic claims about invisible pores between the heart\'s ventricles.',
      'Wrote major commentaries and comprehensive works on medicine and anatomy.',
    ],
    famousQuotes: [],
    awards: ['Remembered as a pioneer of circulatory physiology'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Ibn_al-Nafis',
    isFeatured: false,
  },
  {
    id: '15',
    name: 'Al-Kindi',
    slug: 'al-kindi',
    portraitImage: '/images/scientists/al-kindi.jpg',
    birthDate: 'c. 801',
    deathDate: 'c. 873',
    nationality: 'Arab-Iraqi',
    era: 'Islamic Golden Age',
    field: 'Cryptanalysis & Mathematics',
    group: 'Arab & Muslim Pioneers',
    breakthrough: 'Introduced frequency analysis, a foundational algorithmic method for breaking ciphers.',
    biography: 'Al-Kindi was an Arab polymath at Baghdad\'s House of Wisdom. In his manuscript on deciphering cryptographic messages, he described frequency analysis—using patterns in language statistically to attack substitution ciphers.',
    keyContributions: [
      'Wrote the earliest known detailed explanation of frequency-analysis cryptanalysis.',
      'Helped develop and spread Hindu-Arabic numerals and mathematical methods.',
      'Produced influential work in philosophy, optics, medicine, music, and pharmacology.',
    ],
    famousQuotes: [],
    awards: ['Widely remembered as the father of Arab philosophy and an early cryptanalyst'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Al-Kindi',
    isFeatured: false,
  },
  {
    id: '16',
    name: 'Al-Razi (Rhazes)',
    slug: 'al-razi',
    portraitImage: '/images/scientists/al-razi.jpg',
    birthDate: 'c. 865',
    deathDate: 'c. 925',
    nationality: 'Persian',
    era: 'Islamic Golden Age',
    field: 'Clinical Medicine & Chemistry',
    group: 'Arab & Muslim Pioneers',
    breakthrough: 'Made clinical observation and careful case comparison central to medicine.',
    biography: 'Al-Razi was a physician, hospital director, philosopher, and alchemist. His medical writing emphasized observation and case histories, and his treatise distinguishing smallpox from measles became a landmark in clinical medicine.',
    keyContributions: [
      'Produced an influential clinical distinction between smallpox and measles.',
      'Compiled extensive medical observations and case-based treatments.',
      'Advanced laboratory practice and the classification of chemical substances.',
    ],
    famousQuotes: [],
    awards: ['A lunar crater and the Razi Institute in Iran bear his name'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Abu_Bakr_al-Razi',
    isFeatured: false,
  },
  {
    id: '17',
    name: 'Alan Turing',
    slug: 'alan-turing',
    portraitImage: '/images/scientists/alan-turing.jpg',
    birthDate: '1912-06-23',
    deathDate: '1954-06-07',
    nationality: 'British',
    era: '20th Century',
    field: 'Computer Science & Cryptanalysis',
    group: 'Computing & Algorithms',
    breakthrough: 'Formalized computation and helped prove what algorithms can—and cannot—do.',
    biography: 'Alan Turing gave mathematics a precise model of computation through the Turing machine. He also played a major role in Allied cryptanalysis during the Second World War and later helped shape early computer design and artificial intelligence.',
    keyContributions: [
      'Defined the Turing machine and the modern mathematical concept of computability.',
      'Helped develop methods and machines used against the Enigma cipher.',
      'Proposed the imitation game, now known as the Turing test, for machine intelligence.',
    ],
    famousQuotes: [],
    awards: ['Officer of the Order of the British Empire (1946)', 'The Turing Award is named in his honor'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Alan_Turing',
    isFeatured: true,
  },
  {
    id: '18',
    name: 'Grace Hopper',
    slug: 'grace-hopper',
    portraitImage: '/images/scientists/grace-hopper.jpg',
    birthDate: '1906-12-09',
    deathDate: '1992-01-01',
    nationality: 'American',
    era: '20th Century',
    field: 'Programming Languages',
    group: 'Computing & Algorithms',
    breakthrough: 'Made programming more human-readable through compilers and high-level languages.',
    biography: 'Grace Hopper was a computer scientist and U.S. Navy rear admiral who pioneered machine-independent programming languages. Her compiler work and FLOW-MATIC language helped lead to COBOL and made software accessible far beyond machine code specialists.',
    keyContributions: [
      'Built one of the earliest functioning compiler systems.',
      'Developed FLOW-MATIC and helped shape the COBOL language.',
      'Promoted machine-independent programming and rigorous computer documentation.',
    ],
    famousQuotes: [],
    awards: ['National Medal of Technology (1991)', 'Presidential Medal of Freedom (2016, posthumous)'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Grace_Hopper',
    isFeatured: false,
  },
  {
    id: '19',
    name: 'Claude Shannon',
    slug: 'claude-shannon',
    portraitImage: '/images/scientists/claude-shannon.jpg',
    birthDate: '1916-04-30',
    deathDate: '2001-02-24',
    nationality: 'American',
    era: '20th Century',
    field: 'Information Theory',
    group: 'Computing & Algorithms',
    breakthrough: 'Turned information into a measurable quantity and founded the digital age mathematically.',
    biography: 'Claude Shannon created information theory, establishing the bit as a fundamental unit and proving limits for reliable communication. Earlier, he showed how Boolean logic could design switching circuits, a foundation of digital hardware.',
    keyContributions: [
      'Founded information theory and quantified information in bits.',
      'Established the mathematical limits of data compression and reliable communication.',
      'Connected Boolean algebra to electrical switching circuits.',
    ],
    famousQuotes: [],
    awards: ['National Medal of Science (1966)', 'Kyoto Prize (1985)'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Claude_Shannon',
    isFeatured: false,
  },
  {
    id: '20',
    name: 'Margaret Hamilton',
    slug: 'margaret-hamilton',
    portraitImage: '/images/scientists/margaret-hamilton.jpg',
    birthDate: '1936-08-17',
    nationality: 'American',
    era: '20th-21st Century',
    field: 'Software Engineering',
    group: 'Computing & Algorithms',
    breakthrough: 'Led the fault-tolerant software effort that guided Apollo astronauts to the Moon.',
    biography: 'Margaret Hamilton led the MIT team responsible for the onboard flight software of the Apollo spacecraft. Her work on priority displays, error detection, and recovery demonstrated that software could be engineered as a rigorous, safety-critical discipline.',
    keyContributions: [
      'Directed development of Apollo command and lunar-module flight software.',
      'Advanced priority scheduling, error detection, and recovery in real-time systems.',
      'Helped establish and popularize software engineering as a formal discipline.',
    ],
    famousQuotes: [],
    awards: ['Presidential Medal of Freedom (2016)', 'NASA Exceptional Space Act Award (2003)'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Margaret_Hamilton_(software_engineer)',
    isFeatured: false,
  },
  {
    id: '21',
    name: 'John von Neumann',
    slug: 'john-von-neumann',
    portraitImage: '/images/scientists/john-von-neumann.gif',
    birthDate: '1903-12-28',
    deathDate: '1957-02-08',
    nationality: 'Hungarian-American',
    era: '20th Century',
    field: 'Mathematics & Computer Architecture',
    group: 'Computing & Algorithms',
    breakthrough: 'Helped define the stored-program architecture at the heart of modern computers.',
    biography: 'John von Neumann made foundational contributions across mathematics, quantum physics, economics, and computing. His description of stored-program computer organization became a dominant architecture for general-purpose machines.',
    keyContributions: [
      'Helped formalize stored-program computer architecture.',
      'Co-founded game theory and advanced numerical computation.',
      'Developed foundational ideas in cellular automata and self-replicating systems.',
    ],
    famousQuotes: [],
    awards: ['Medal for Merit (1946)', 'Enrico Fermi Award (1956)'],
    sourceUrl: 'https://en.wikipedia.org/wiki/John_von_Neumann',
    isFeatured: false,
  },
  {
    id: '22',
    name: 'Charles Darwin',
    slug: 'charles-darwin',
    portraitImage: '/images/scientists/charles-darwin.jpg',
    birthDate: '1809-02-12',
    deathDate: '1882-04-19',
    nationality: 'English',
    era: '19th Century',
    field: 'Evolutionary Biology',
    group: 'Life Sciences',
    breakthrough: 'Explained the diversity of life through evolution by natural selection.',
    biography: 'Charles Darwin developed the theory of evolution by natural selection, integrating observations from geology, animal breeding, biogeography, and the voyage of HMS Beagle. The theory unified biology around common descent and change over time.',
    keyContributions: [
      'Formulated evolution by natural selection alongside Alfred Russel Wallace.',
      'Established common descent as a unifying explanation for biological diversity.',
      'Applied evolutionary reasoning to human origins, behavior, and ecology.',
    ],
    famousQuotes: [],
    awards: ['Copley Medal (1864)', 'Buried in Westminster Abbey'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Charles_Darwin',
    isFeatured: true,
  },
  {
    id: '23',
    name: 'Galileo Galilei',
    slug: 'galileo-galilei',
    portraitImage: '/images/scientists/galileo-galilei.jpg',
    birthDate: '1564-02-15',
    deathDate: '1642-01-08',
    nationality: 'Italian',
    era: '16th-17th Century',
    field: 'Astronomy & Physics',
    group: 'Physical Sciences',
    breakthrough: 'Used telescopic evidence and experiment to transform astronomy and motion.',
    biography: 'Galileo Galilei combined mathematics, experiment, and improved telescopes to challenge the inherited picture of the cosmos. His observations supported heliocentrism, while his studies of falling bodies helped lay the foundations of classical mechanics.',
    keyContributions: [
      'Observed Jupiter\'s moons, Venus\'s phases, sunspots, and the Moon\'s rugged surface.',
      'Established quantitative laws for falling bodies and accelerated motion.',
      'Championed experiment and mathematical description in physical science.',
    ],
    famousQuotes: [],
    awards: ['A lunar crater and the Galileo spacecraft bear his name'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Galileo_Galilei',
    isFeatured: false,
  },
  {
    id: '24',
    name: 'Louis Pasteur',
    slug: 'louis-pasteur',
    portraitImage: '/images/scientists/louis-pasteur.jpg',
    birthDate: '1822-12-27',
    deathDate: '1895-09-28',
    nationality: 'French',
    era: '19th Century',
    field: 'Microbiology & Medicine',
    group: 'Life Sciences',
    breakthrough: 'Established germ theory applications that transformed medicine, food safety, and vaccination.',
    biography: 'Louis Pasteur demonstrated that microorganisms drive fermentation and can cause disease. His work led to pasteurization, strengthened germ theory, and produced vaccines that helped establish microbiology and modern public health.',
    keyContributions: [
      'Showed the microbial basis of fermentation and supported germ theory.',
      'Developed pasteurization to reduce harmful microorganisms in food and drink.',
      'Created vaccines for rabies and anthrax using attenuation techniques.',
    ],
    famousQuotes: [],
    awards: ['Copley Medal (1874)', 'Grand Cross of the Legion of Honour (1881)'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Louis_Pasteur',
    isFeatured: true,
  },
  {
    id: '25',
    name: 'Rosalind Franklin',
    slug: 'rosalind-franklin',
    portraitImage: '/images/scientists/rosalind-franklin.jpg',
    birthDate: '1920-07-25',
    deathDate: '1958-04-16',
    nationality: 'British',
    era: '20th Century',
    field: 'Chemistry & Molecular Biology',
    group: 'Life Sciences',
    breakthrough: 'Produced decisive X-ray evidence for the molecular structure of DNA.',
    biography: 'Rosalind Franklin was a chemist and X-ray crystallographer whose precise diffraction work was central to understanding DNA\'s double-helical structure. She also made major contributions to the structures of coal, graphite, and viruses.',
    keyContributions: [
      'Captured and analyzed exceptionally clear X-ray diffraction images of DNA.',
      'Determined key dimensions and hydration features of DNA\'s helical structure.',
      'Advanced structural research on coal, graphite, and plant viruses.',
    ],
    famousQuotes: [],
    awards: ['The Rosalind Franklin rover and many scientific awards bear her name'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Rosalind_Franklin',
    isFeatured: false,
  },
  {
    id: '26',
    name: 'Michael Faraday',
    slug: 'michael-faraday',
    portraitImage: '/images/scientists/michael-faraday.jpg',
    birthDate: '1791-09-22',
    deathDate: '1867-08-25',
    nationality: 'English',
    era: '19th Century',
    field: 'Electromagnetism & Chemistry',
    group: 'Physical Sciences',
    breakthrough: 'Discovered electromagnetic induction, making motors, generators, and modern power possible.',
    biography: 'Michael Faraday was a self-taught experimental physicist and chemist who revealed the deep relationship between electricity and magnetism. His discoveries made electric motors, transformers, and generators possible and introduced the field concept to physics.',
    keyContributions: [
      'Discovered electromagnetic induction and built an early electric generator.',
      'Established the laws of electrolysis and advanced electrochemistry.',
      'Introduced physical lines of force and discovered the Faraday effect.',
    ],
    famousQuotes: [],
    awards: ['Royal Medal (1835 and 1846)', 'The SI unit farad is named in his honor'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Michael_Faraday',
    isFeatured: false,
  },
];

export const DEMO_SCIENTISTS: ScientistProfile[] = BASE_SCIENTISTS.map((profile) => ({
  ...profile,
  biography: SCIENTIST_BIOGRAPHIES[profile.slug] || profile.biography,
}));

export function mergeScientistProfiles(remoteScientists: ScientistListItem[]): ScientistProfile[] {
  const remoteBySlug = new Map(remoteScientists.map((scientist) => [scientist.slug, scientist]));

  const mergedDemo = DEMO_SCIENTISTS.map((profile) => {
    const remote = remoteBySlug.get(profile.slug);
    if (!remote) return profile;

    remoteBySlug.delete(profile.slug);
    return {
      ...profile,
      ...remote,
      group: remote.group ?? profile.group,
      breakthrough: remote.breakthrough ?? profile.breakthrough,
      sourceUrl: remote.sourceUrl ?? profile.sourceUrl,
      portraitImage: profile.portraitImage,
    };
  });

  const remoteOnly = Array.from(remoteBySlug.values()).map((scientist) => ({
    ...scientist,
    biography: '',
    keyContributions: [],
    famousQuotes: [],
    awards: [],
  }));

  return [...mergedDemo, ...remoteOnly];
}
