// Original contextual biographies written for ScienceHub.
// Dates and attribution are kept cautious where medieval records are incomplete.

export const SCIENTIST_BIOGRAPHIES: Record<string, string> = {
  'albert-einstein': `Albert Einstein reshaped physics by asking what the laws of nature would look like to observers moving relative to one another. His 1905 work connected space and time, explained Brownian motion, described the photoelectric effect using light quanta, and established mass-energy equivalence. A decade later, general relativity replaced gravitational force with a geometric account of curved spacetime.

Einstein’s career also shows that scientific influence extends beyond a single theory. He challenged aspects of quantum mechanics, helped establish statistical physics, and used thought experiments to expose hidden assumptions. Experiments have repeatedly confirmed predictions of relativity, while his debates about quantum completeness helped motivate later work on entanglement. His political life included opposition to nationalism and persecution, emigration from Nazi Germany, and public advocacy concerning nuclear weapons and civil liberties.`,

  'marie-curie': `Marie Curie developed methods for measuring and separating radioactive substances at a time when atomic physics was still taking shape. Working with Pierre Curie and drawing on Henri Becquerel’s observations, she showed that radiation was linked to the atom itself rather than to an ordinary chemical reaction. The search led to the identification of polonium and radium and to years of difficult separation work with uranium ore.

Curie became the first person awarded Nobel Prizes in two different sciences. During the First World War, she helped organize mobile radiography units and trained operators, bringing X-ray imaging closer to wounded soldiers. Her laboratories influenced nuclear physics, chemistry, and medicine, although the health risks of prolonged radiation exposure were not yet understood. Her career also reveals the institutional barriers faced by women in European science and the persistence required to build authority inside them.`,

  'nikola-tesla': `Nikola Tesla was an electrical engineer and inventor whose most durable work concerned alternating-current power. His polyphase system created rotating magnetic fields that could drive induction motors efficiently, while transformers allowed voltage to be raised for transmission and lowered for practical use. These ideas became central to large electrical grids.

Tesla also investigated high-frequency currents, resonant circuits, lighting, radio control, and wireless transmission. Public memory often mixes his documented engineering with exaggerated claims, so patents, demonstrations, and contemporary records matter when evaluating a story. His Wardenclyffe project did not become a working global power system, and several later proposals remained speculative. Tesla’s real achievements need no mythology: he helped make long-distance electrical power practical and expanded the experimental language of high-voltage engineering.`,

  'stephen-hawking': `Stephen Hawking studied gravity where general relativity, thermodynamics, and quantum theory meet. With Roger Penrose, he developed singularity theorems showing that gravitational collapse and cosmic expansion create deep limits for classical spacetime under broad conditions. His best-known result was that black holes should emit thermal radiation when quantum fields are considered near an event horizon.

Hawking radiation implied that black holes have temperature and entropy and may eventually evaporate. That connection produced the black-hole information problem, which remains a major test for proposed theories of quantum gravity. Hawking also worked on early-universe cosmology and the conditions that might replace a classical beginning. Alongside research, he became an unusually influential public communicator, showing that severe motor neurone disease did not prevent a long intellectual career, while relying on extensive personal, technical, and institutional support.`,

  'isaac-newton': `Isaac Newton unified terrestrial and celestial motion through mathematical laws that related force, mass, acceleration, and gravitation. In the Principia, he showed that the same framework could explain falling bodies, planetary orbits, tides, and the paths of comets. His development of fluxional methods formed part of the emergence of calculus, independently developed in another notation by Gottfried Wilhelm Leibniz.

Newton’s optical experiments demonstrated that white light contains a spectrum of colours and led him to build a practical reflecting telescope. His career was not an isolated sequence of inspirations: it drew on Kepler, Galileo, Descartes, Huygens, and a network of correspondence. He also spent enormous effort on alchemy, theology, chronology, and government service at the Royal Mint. Modern physics has revised Newton’s framework at relativistic and quantum scales, but it remains exceptionally accurate across much of engineering and astronomy.`,

  'ada-lovelace': `Ada Lovelace encountered Charles Babbage’s plans for the Analytical Engine through mathematics, correspondence, and Britain’s scientific social networks. Her translation of Luigi Menabrea’s account became far more substantial through a series of notes explaining how the proposed machine might operate. One note described a procedure for calculating Bernoulli numbers and is often discussed as an early published computer program.

The Analytical Engine was never completed, so claims about a fully functioning nineteenth-century software practice would be misleading. Lovelace’s deeper contribution was conceptual. She distinguished the machine’s symbolic operations from mere arithmetic and considered how numbers might represent entities such as musical relationships. Historians continue to debate how credit should be divided between Lovelace, Babbage, and their collaborators. The surviving record nevertheless shows a serious mathematical author thinking beyond calculation toward general-purpose symbolic processing.`,

  'al-khwarizmi': `Muhammad ibn Musa al-Khwarizmi worked in ninth-century Baghdad, where translation, astronomy, geography, and calculation were supported around the Abbasid court. His treatise on calculation by completion and balancing presented systematic methods for solving classes of linear and quadratic problems. The title supplied the later word “algebra,” while Latin forms of his name contributed to the word “algorithm.”

Al-Khwarizmi did not invent every technique in isolation. His writing organized and explained knowledge connected to earlier Indian, Greek, and regional traditions. Works associated with him helped transmit decimal positional calculation, astronomical tables, and geographical methods. Surviving texts and later translations do not always preserve an uncomplicated original, so historians distinguish his documented works from broad legends. His lasting importance lies in making procedures explicit, general, and teachable across languages and centuries.`,

  'ibn-al-haytham': `Ibn al-Haytham, known in Latin as Alhazen, produced an extensive investigation of vision, light, reflection, and refraction. He rejected accounts in which rays were emitted by the eye and instead analysed vision as light entering the eye from illuminated objects. His Book of Optics combined geometry with carefully described observations and experiments.

His work examined mirrors, lenses, atmospheric effects, and the conditions under which perception can be mistaken. Calling him the sole inventor of “the scientific method” would impose a modern label on a much longer history. A more accurate achievement is that he joined mathematical modelling, controlled arrangements, and criticism of earlier authorities in an unusually sustained way. Latin translations later influenced European optics, while his arguments remain important evidence of the rich scientific scholarship developed in the medieval Islamic world.`,

  'ibn-sina': `Ibn Sina, or Avicenna, was a Persian physician and philosopher whose writings attempted to organize medicine, natural philosophy, logic, and metaphysics into coherent systems. The Canon of Medicine compared diseases, symptoms, drugs, and therapeutic reasoning, drawing on Greek, Persian, Indian, and Islamic medical traditions as well as his own clinical experience.

The Canon became a major reference in parts of the Islamic world and, through Latin translation, in European universities. It should not be read as modern medicine: it contains humoral theory and treatments later abandoned. Its historical value lies in classification, differential observation, pharmacological discussion, and the effort to make medical knowledge teachable. Ibn Sina’s philosophical works were equally influential, especially his arguments about existence, causation, mind, and knowledge. His legacy belongs to both the history of medicine and the history of philosophy.`,

  'al-zahrawi': `Abu al-Qasim al-Zahrawi was a physician associated with Cordoba in al-Andalus. His large medical compendium, al-Tasrif, surveyed medical practice and included an influential section on surgery. It described instruments, procedures, cauterization, wound care, fractures, dentistry, and obstetric problems, often pairing written instructions with illustrations.

The survival and later translation of al-Tasrif helped transmit surgical knowledge into Latin-reading Europe. Historical descriptions sometimes present al-Zahrawi as if he invented every instrument shown in the text; some tools and procedures had older precedents. His distinctive achievement was to document operative practice systematically and to treat surgery as skilled medical work requiring anatomy, preparation, and follow-up. The record also reminds modern readers that medieval medicine contained practical traditions alongside theories that would later be revised or rejected.`,

  'al-biruni': `Al-Biruni was a Central Asian scholar whose work ranged across astronomy, mathematics, geography, chronology, mineralogy, and the comparative study of cultures. He used geometry and astronomical observation to investigate Earth’s dimensions and locations, and he wrote carefully about calendars and methods for coordinating different systems of time.

During years connected with the Ghaznavid court, al-Biruni studied Indian languages, scholarship, religion, and mathematics. His account of India is notable for trying to describe ideas in their own terms, though it still reflects the limits and context of an eleventh-century observer. He compared measurements, reported methods, and often separated what he had observed from what others claimed. Rather than fitting one modern profession, al-Biruni represents a scholarly world in which mathematical technique linked the heavens, Earth, materials, and human history.`,

  'jabir-ibn-hayyan': `Jabir ibn Hayyan is associated with a large Arabic corpus on alchemy, substances, laboratory operations, medicine, and natural philosophy. Historians do not agree that every work in this “Jabirian corpus” was written by one person; many texts may have developed within a later intellectual tradition using Jabir’s name. That uncertainty is part of the history, not a detail to hide.

The corpus discusses processes such as distillation, calcination, crystallization, and the preparation of materials. It combines practical operations with symbolic and philosophical theories that differ from modern chemistry. Claims that Jabir single-handedly invented particular acids or all experimental chemistry are too simple for the surviving evidence. His importance lies in the scale and influence of the textual tradition and in its picture of systematic material investigation in the medieval Islamic world.`,

  'al-jazari': `Al-Jazari was an engineer in the Artuqid court who described elaborate water-raising machines, clocks, fountains, vessels, and automata. His Book of Knowledge of Ingenious Mechanical Devices paired explanations with detailed coloured illustrations, making it possible to study how components were intended to fit and move.

The machines used floats, valves, siphons, gears, cams, and controlled water flow to produce timed motion and visual performance. They were not robots in the modern electronic sense, but some embodied programmable sequences of mechanical actions. Al-Jazari’s value is both technical and documentary: he explained construction rather than merely celebrating novelty. Reproductions indicate that many mechanisms are workable, although manuscripts can differ and historical devices may not survive. His work connects precision engineering with courtly art, public display, and practical hydraulic knowledge.`,

  'ibn-al-nafis': `Ibn al-Nafis was a thirteenth-century physician who wrote commentaries and original medical works in Damascus and Cairo. In his commentary on anatomy, he argued that blood from the right side of the heart reaches the left side through the lungs rather than through invisible pores in the heart’s dividing wall. This description is recognized as an important account of pulmonary circulation.

His model was not the complete modern circulation later associated with William Harvey, and it remained embedded in medieval physiology. Its significance is that Ibn al-Nafis criticized an authoritative anatomical claim and proposed a route more consistent with the structure of the heart and lungs. Manuscript rediscovery in the twentieth century changed common histories of circulation, illustrating how language, archival survival, and transmission determine which scientific contributions become widely known.`,

  'al-kindi': `Al-Kindi worked in the intellectual world of ninth-century Baghdad and wrote across philosophy, mathematics, optics, music, medicine, and cryptanalysis. He helped develop an Arabic philosophical vocabulary capable of engaging Greek works while arguing that imported knowledge could be examined rather than accepted uncritically.

A treatise attributed to al-Kindi gives an early clear description of frequency analysis for breaking substitution ciphers: count how often symbols appear and compare the pattern with letter frequencies in the language. The method links statistics, language, and secrecy in a way recognizable to modern cryptography. His musical writings treated intervals through numerical ratios, while his optical and medical works joined calculation with natural philosophy. Because the surviving corpus includes uncertain attributions, careful accounts distinguish documented texts from later claims made in his name.`,

  'al-razi': `Al-Razi, known in Latin as Rhazes, was a Persian physician, hospital director, and philosophical author. His clinical writings compared symptoms and case histories and attempted to distinguish diseases that could look similar. A famous treatise differentiated smallpox from measles more clearly than many earlier accounts, although its explanations and treatments belong to premodern medicine.

Al-Razi valued observation and criticized authorities when experience did not match inherited claims. Works associated with him discuss pharmacy, diet, ethics, and the organization of care. Stories about his hospital practice are sometimes repeated without strong contemporary evidence, so his reputation should rest on the substantial texts that survive. Those writings show medicine developing through compilation, comparison, bedside experience, and debate across Greek, Persian, Indian, and Arabic traditions.`,

  'alan-turing': `Alan Turing helped define what computation means before electronic general-purpose computers were practical. His abstract machine model showed how a simple rule-following device could represent any effective calculation and allowed him to prove that some problems are not computable. The same work clarified the idea of a universal machine whose behaviour is determined by stored instructions.

During the Second World War, Turing contributed to British cryptanalysis at Bletchley Park, especially methods and machines used against Enigma traffic. Later he worked on early computer design, machine intelligence, and mathematical biology, including patterns produced by reacting and diffusing chemicals. Turing was prosecuted in 1952 for homosexual activity and subjected to hormonal treatment; he died in 1954. His treatment demonstrates how institutions can persecute the very people whose work they depend on.`,

  'grace-hopper': `Grace Hopper combined mathematics, naval service, programming, and unusually effective technical communication. Working with the Harvard Mark I team during the Second World War, she prepared calculations and documentation for an electromechanical computer. At Eckert-Mauchly and Remington Rand, she advocated tools that allowed programmers to use more familiar symbolic instructions instead of writing every operation at machine level.

Hopper’s compiler work and the FLOW-MATIC language influenced the development of COBOL, a language designed for business data processing. She did not single-handedly invent compilers or COBOL, but she was a central advocate and organizer in the teams that made higher-level programming practical. Her naval career continued for decades, and her lectures used concrete demonstrations, including lengths of wire representing nanoseconds, to make computing performance understandable to broad audiences.`,

  'claude-shannon': `Claude Shannon established a mathematical theory of communication that separated information from the particular meaning of a message. He represented uncertainty using entropy and showed how channel capacity, noise, compression, and error correction could be analysed in a common framework. The theory applies whether symbols travel through a wire, radio link, optical fibre, or storage medium.

Earlier, Shannon’s master’s thesis connected Boolean algebra with switching circuits, providing a foundation for digital logic design. His later work ranged across cryptography, probability, chess-playing machines, and playful mechanical devices. Information theory does not claim that human meaning can be reduced entirely to bits; it deliberately addresses the reliable representation and transmission of choices. That abstraction became powerful because it revealed limits and design principles shared by many communication systems.`,

  'margaret-hamilton': `Margaret Hamilton led software engineering work for the Apollo guidance computer at the MIT Instrumentation Laboratory. Her teams developed onboard flight software that had to operate with limited memory, respond in real time, prioritize critical tasks, and recover from some unexpected conditions. During Apollo 11’s descent, priority scheduling helped the computer continue essential guidance despite overload alarms.

Apollo software was a collective achievement involving programmers, engineers, astronauts, contractors, and mission controllers. Hamilton’s leadership is important partly because software was often treated as secondary to hardware even when mission safety depended on it. She later founded companies focused on software reliability and formalized ideas about system design and error prevention. Her career helped make software engineering visible as a discipline requiring architecture, testing, documentation, and responsibility rather than improvised coding.`,

  'john-von-neumann': `John von Neumann made foundational contributions to mathematics, quantum theory, economics, computing, and the analysis of complex systems. His work included operator theory, game theory with Oskar Morgenstern, mathematical formulations of quantum mechanics, and numerical methods for problems that could not be solved analytically.

In computing, von Neumann’s name is associated with stored-program architecture, in which instructions and data occupy memory accessible to the processor. The idea emerged through collaborative wartime and postwar projects, and historians caution against assigning the architecture to one person. Von Neumann’s reports nevertheless helped articulate and circulate the design. He also worked on nuclear weapons and strategic policy, parts of his career that raise questions about scientific responsibility. His range illustrates both the unity of mathematical methods and their consequences when applied to state power.`,

  'charles-darwin': `Charles Darwin developed the theory of evolution by natural selection through decades of observation, reading, correspondence, specimen study, and argument. The voyage of HMS Beagle exposed him to geological change and biological variation, but the theory emerged later as he compared domestication, population pressure, geographic distribution, fossils, and relationships among species.

Alfred Russel Wallace independently reached a similar principle, prompting joint presentation in 1858 before Darwin published On the Origin of Species. Modern evolutionary biology has added genetics, molecular evidence, developmental biology, and population mathematics that Darwin did not possess. Some of Darwin’s writing also reflected Victorian racial and social assumptions that should be examined rather than excused. Natural selection remains central because it generates testable explanations for adaptation and diversity, not because every nineteenth-century statement was correct.`,

  'galileo-galilei': `Galileo Galilei joined mathematical analysis, experiment, and improved instruments to investigate motion and the heavens. His telescopic observations revealed mountains on the Moon, moons orbiting Jupiter, phases of Venus, and an abundance of stars invisible to the naked eye. These findings challenged simple geocentric arrangements and the traditional picture of perfect unchanging heavens.

His studies of falling bodies and projectiles helped replace qualitative Aristotelian accounts with mathematical relationships. Galileo did not invent the telescope, nor did one observation alone prove heliocentrism. His importance lies in turning an instrument toward systematic astronomical questions and arguing publicly from the results. Conflict with Church authorities involved scriptural interpretation, patronage, personality, and the evidence available at the time; reducing it to “science versus religion” loses much of the history.`,

  'louis-pasteur': `Louis Pasteur used chemistry and carefully designed experiments to study fermentation, spoilage, and infectious disease. Work on molecular asymmetry helped establish his scientific reputation before he showed that particular microorganisms could drive particular fermentations. Experiments with controlled exposure challenged spontaneous-generation claims under the conditions tested and strengthened the emerging germ theory of disease.

Pasteur and collaborators developed vaccines against diseases including chicken cholera, anthrax, and rabies, although methods, credit, and public demonstrations were more complicated than heroic accounts suggest. His laboratory combined research, industry, agriculture, and medicine and became a model for institutes that connected basic science with public health. Pasteur did not create germ theory alone; figures including Agostino Bassi, Ignaz Semmelweis, Joseph Lister, and Robert Koch contributed distinct evidence and practices.`,

  'rosalind-franklin': `Rosalind Franklin was a physical chemist and X-ray crystallographer whose measurements clarified the structures of carbon materials, DNA, and viruses. At King’s College London, she and Raymond Gosling produced exceptionally informative diffraction images and quantitative analyses of DNA fibres. Her work distinguished structural forms and constrained dimensions essential to building a correct molecular model.

Data from her group were shown to James Watson without her direct permission, and an internal report containing her results was available to Francis Crick. Watson and Crick’s double-helix model drew on several lines of evidence, including Franklin’s measurements and Erwin Chargaff’s chemical ratios. Franklin later led productive research on tobacco mosaic virus and poliovirus at Birkbeck College. She died before the 1962 Nobel Prize and is best understood as an accomplished scientist, not merely as a missing footnote to someone else’s discovery.`,

  'michael-faraday': `Michael Faraday rose from an apprenticeship in bookbinding to become one of the nineteenth century’s most inventive experimental scientists. At the Royal Institution, he discovered electromagnetic induction: a changing magnetic environment can produce an electric current. This principle underlies generators and transformers and linked electricity, magnetism, and motion in a new experimental framework.

Faraday also built early motors, established quantitative laws of electrolysis, investigated materials and gases, and discovered how magnetism can affect polarized light. He described fields through physical lines of force before later mathematics gave the concept a more formal expression. Faraday’s public lectures, especially the Chemical History of a Candle, showed the same discipline as his laboratory work: begin with an ordinary phenomenon, isolate processes carefully, and connect observations without pretending the evidence says more than it does.`,
};
